CREATE DATABASE todo_php CHARACTER SET UTF8;

USE todo_php;

CREATE TABLE task (
  ID SERIAL ,
  TITLE CHAR(100) NOT NULL ,
  SCHEDULE_DATE CHAR(10) NOT NULL ,
  FINISH_DATE CHAR(10) ,
  RANK CHAR(1) NOT NULL,
  FINISH_CHECK INT(1) NOT NULL,
  PRIMARY KEY (ID)
);
